stages:
  load_data:
    cmd: python src/stage_01_load_and_save.py -c config/config.yaml
    deps:
      - src\stage_01_load_and_save.py
      - src\utils\all_utils.py
      - config\config.yaml
    outs:
      - artifacts\raw_local_dir\data.csv
  
  split_data:
    cmd: python src/stage_02_split_data.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_02_split_data.py
      - src\utils\all_utils.py
      - config\config.yaml
      - artifacts\raw_local_dir\data.csv
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts\split_data_dir\train.csv
      - artifacts\split_data_dir\test.csv
  
  training:
    cmd: python src/stage_03_train.py -c config/config.yaml -p params.yaml
    deps:
      - src\stage_03_train.py
      - src\utils\all_utils.py
      - config\config.yaml
    params:
      - base.random_state
      - model_params.random_forest.model_name
      - model_params.random_forest.n_estimators
      - model_params.random_forest.max_depth
      - model_params.random_forest.max_features
      - model_params.random_forest.min_samples_split
      - model_params.random_forest.min_samples_leaf
    outs:
      - artifacts\model_dir\Random_Forest.pkl
      - artifacts\model_dir\XGBoost.pkl