base:
  random_state: 42
  test_size: 0.2

model_params:
  random_forest:
    model_name: RandomForestClassifier
    n_estimators: 100
    max_depth: 3
    max_features: 'sqrt'
    min_samples_split: 2
    min_samples_leaf: 1
  
  xgboost:
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    objective: 'reg:linear'
    gamma: 0
    min_child_weight: 1
    max_delta_step: 0
