data_source: C:\Rishav_python\DVC\Loan_Prediction\Notebooks\train_cleaned.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv
  
  model_dir: model_dir
  model_file_random_forest: Random_Forest.pkl
  model_file_xgboost: XGBoost.pkl

  report_dir: report_dir
  rf_score: rf_score.json
  xgb_score: xgb_score.json
  